import type { ProviderPreset } from "./providerTypes";
import type { IconName } from "./ui/icons";

const ICON_OPENAI: IconName = "sparkles";
const ICON_ANTHROPIC: IconName = "brain";
const ICON_GOOGLE: IconName = "sparkle";
const ICON_XAI: IconName = "zap";
const ICON_MISTRAL: IconName = "idea";
const ICON_DEEPSEEK: IconName = "terminal";
const ICON_TOGETHER: IconName = "users";
const ICON_GROQ: IconName = "lightning";
const ICON_FIREWORKS: IconName = "fire";
const ICON_COHERE: IconName = "compass";
const ICON_OPENROUTER: IconName = "swap";
const ICON_OLLAMA: IconName = "server";
const ICON_LMSTUDIO: IconName = "home";
const ICON_AZURE: IconName = "cloud";
const ICON_HERMES: IconName = "robot";
const ICON_OPENCODE: IconName = "terminal";
const ICON_MINIMAX: IconName = "sparkle";
const ICON_MIMO: IconName = "zap";
const ICON_ZAI: IconName = "brain";
const ICON_MOONSHOT: IconName = "idea";

export const providerPresets: ProviderPreset[] = [
  {
    id: "openai",
    name: "OpenAI",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_OPENAI,
    apiURL: "https://api.openai.com/v1/",
    authMethod: "bearer",
    apiKeyPlaceholder: "sk-...",
    defaultModel: "gpt-5-mini",
    supportsModelDiscovery: true,
    adapterId: "openai-compatible",
    verifiedCapabilities: ["chat", "embedding", "image", "video", "tts", "stt"],
  },
  {
    id: "anthropic",
    name: "Anthropic (Claude)",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_ANTHROPIC,
    apiURL: "https://api.anthropic.com/v1/",
    authMethod: "x-api-key",
    authHeaderName: "x-api-key",
    authPrefix: "",
    extraHeaders: { "anthropic-version": "2023-06-01" },
    apiKeyPlaceholder: "sk-ant-...",
    defaultModel: "claude-sonnet-4.5",
    supportsModelDiscovery: true,
    adapterId: "anthropic",
    verifiedCapabilities: ["chat"],
    notes: "Uses x-api-key header, not standard Bearer token",
  },
  {
    id: "google",
    name: "Google Gemini",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_GOOGLE,
    apiURL: "https://generativelanguage.googleapis.com/v1beta/openai/",
    authMethod: "bearer",
    apiKeyPlaceholder: "AIza...",
    defaultModel: "gemini-2.5-flash",
    supportsModelDiscovery: true,
    adapterId: "openai-compatible",
    verifiedCapabilities: ["chat", "embedding", "image"],
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_XAI,
    apiURL: "https://api.x.ai/v1/",
    authMethod: "bearer",
    apiKeyPlaceholder: "xai-...",
    defaultModel: "grok-4.1-fast",
    supportsModelDiscovery: true,
    verifiedCapabilities: ["chat", "image", "video", "tts", "stt"],
    catalogModels: [
      { id: "grok-voice-latest", capabilities: ["tts"] },
      { id: "grok-transcribe", capabilities: ["stt"] },
    ],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_MISTRAL,
    apiURL: "https://api.mistral.ai/v1/",
    authMethod: "bearer",
    defaultModel: "mistral-large-latest",
    supportsModelDiscovery: true,
    verifiedCapabilities: ["chat", "embedding", "tts", "stt"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_DEEPSEEK,
    apiURL: "https://api.deepseek.com/v1/",
    authMethod: "bearer",
    defaultModel: "deepseek-chat",
    supportsModelDiscovery: true,
    verifiedCapabilities: ["chat"],
  },
  {
    id: "together",
    name: "Together AI",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_TOGETHER,
    apiURL: "https://api.together.xyz/v1/",
    authMethod: "bearer",
    defaultModel: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
    supportsModelDiscovery: true,
    adapterId: "together",
    verifiedCapabilities: ["chat", "embedding", "image", "video", "tts", "stt"],
    catalogModels: [
      { id: "openai/sora-2-pro", capabilities: ["video"] },
      { id: "cartesia/sonic-3", capabilities: ["tts"] },
      { id: "hexgrad/Kokoro-82M", capabilities: ["tts"] },
      { id: "openai/whisper-large-v3", capabilities: ["stt"] },
      { id: "deepgram/nova-3-en", capabilities: ["stt"] },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_GROQ,
    apiURL: "https://api.groq.com/openai/v1/",
    authMethod: "bearer",
    apiKeyPlaceholder: "gsk_...",
    defaultModel: "llama-3.3-70b-versatile",
    supportsModelDiscovery: true,
    verifiedCapabilities: ["chat", "tts", "stt"],
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_FIREWORKS,
    apiURL: "https://api.fireworks.ai/inference/v1/",
    authMethod: "bearer",
    apiKeyPlaceholder: "fw_...",
    defaultModel: "accounts/fireworks/models/llama-v3p3-70b-instruct",
    supportsModelDiscovery: true,
    verifiedCapabilities: ["chat", "embedding"],
    notes:
      "Image models use Fireworks workflow endpoints and require a per-model endpoint override.",
  },
  {
    id: "cohere",
    name: "Cohere",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_COHERE,
    apiURL: "https://api.cohere.com/compatibility/v1/",
    modelsURL: "https://api.cohere.com/v1/models?page_size=1000",
    authMethod: "bearer",
    defaultModel: "command-r-plus",
    supportsModelDiscovery: true,
    verifiedCapabilities: ["chat", "embedding"],
  },
  {
    id: "minimax",
    name: "MiniMax",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_MINIMAX,
    apiURL: "https://api.minimax.io/v1",
    authMethod: "bearer",
    apiKeyPlaceholder: "sk-... or sk-cp-...",
    defaultModel: "MiniMax-M3",
    supportsModelDiscovery: true,
    adapterId: "openai-compatible",
    verifiedCapabilities: ["chat", "image", "video", "tts"],
    catalogModels: [
      { id: "image-01", capabilities: ["image"] },
      { id: "MiniMax-Hailuo-2.3", capabilities: ["video"] },
      { id: "MiniMax-Hailuo-02", capabilities: ["video"] },
      { id: "speech-2.8-hd", capabilities: ["tts"] },
      { id: "speech-2.8-turbo", capabilities: ["tts"] },
    ],
    notes:
      "General API and Token Plan coding access use the same OpenAI-compatible URL.",
  },
  {
    id: "mimo",
    name: "Xiaomi MiMo",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_MIMO,
    apiURL: "https://api.xiaomimimo.com/v1",
    authMethod: "bearer",
    apiKeyPlaceholder: "sk-...",
    defaultModel: "mimo-v2.5-pro",
    supportsModelDiscovery: false,
    adapterId: "mimo",
    verifiedCapabilities: ["chat", "tts", "stt"],
    catalogModels: [
      { id: "mimo-v2.5-pro", capabilities: ["chat"], contextLength: 1000000 },
      { id: "mimo-v2.5", capabilities: ["chat"], contextLength: 1000000 },
      { id: "mimo-v2-flash", capabilities: ["chat"], contextLength: 256000 },
      { id: "mimo-v2.5-asr", capabilities: ["stt"], contextLength: 8000 },
      { id: "mimo-v2.5-tts", capabilities: ["tts"], contextLength: 8000 },
      {
        id: "mimo-v2.5-tts-voiceclone",
        capabilities: ["tts"],
        contextLength: 8000,
      },
      {
        id: "mimo-v2.5-tts-voicedesign",
        capabilities: ["tts"],
        contextLength: 8000,
      },
    ],
    notes:
      "Pay-as-you-go API. Token Plan users must replace this URL with the OpenAI-compatible Base URL shown on their Token Plan page.",
  },
  {
    id: "zai",
    name: "Z.AI",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_ZAI,
    apiURL: "https://api.z.ai/api/paas/v4",
    authMethod: "bearer",
    apiKeyPlaceholder: "Z.AI API key",
    defaultModel: "glm-5.1",
    supportsModelDiscovery: true,
    adapterId: "openai-compatible",
    verifiedCapabilities: ["chat", "image", "video"],
    catalogModels: [
      { id: "glm-image", capabilities: ["image"] },
      { id: "cogvideox-3", capabilities: ["video"] },
    ],
    notes: "General pay-as-you-go API.",
  },
  {
    id: "zai-coding",
    name: "Z.AI Coding Plan",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_ZAI,
    apiURL: "https://api.z.ai/api/coding/paas/v4",
    authMethod: "bearer",
    apiKeyPlaceholder: "Z.AI Coding Plan API key",
    defaultModel: "glm-5.1",
    supportsModelDiscovery: true,
    adapterId: "openai-compatible",
    verifiedCapabilities: ["chat"],
    notes: "Dedicated endpoint for GLM Coding Plan subscriptions.",
  },
  {
    id: "moonshot",
    name: "Moonshot AI (Kimi)",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_MOONSHOT,
    apiURL: "https://api.moonshot.ai/v1",
    authMethod: "bearer",
    apiKeyPlaceholder: "Moonshot API key",
    defaultModel: "kimi-k2.7-code",
    supportsModelDiscovery: true,
    adapterId: "openai-compatible",
    verifiedCapabilities: ["chat"],
    notes:
      "Kimi coding models use the standard Moonshot API URL; no separate coding endpoint is required.",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_OPENROUTER,
    apiURL: "https://openrouter.ai/api/v1/",
    modelsURL: "https://openrouter.ai/api/v1/models?output_modalities=all",
    authMethod: "bearer",
    apiKeyPlaceholder: "sk-or-...",
    defaultModel: "openai/gpt-5-mini",
    supportsModelDiscovery: true,
    adapterId: "openrouter",
    verifiedCapabilities: ["chat", "embedding", "image", "video", "tts", "stt"],
    notes: "Meta-router: access 500+ models from 60+ providers with one key",
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    icon: ICON_OPENCODE,
    apiURL: "https://opencode.ai/zen/go/v1",
    modelsURL: "https://opencode.ai/zen/go/v1/models",
    authMethod: "bearer",
    apiKeyPlaceholder: "OpenCode API key",
    requiresApiKey: true,
    isLocal: false,
    supportsModelDiscovery: true,
    adapterId: "openai-compatible",
    verifiedCapabilities: ["chat"],
    notes:
      "Only models documented for /chat/completions are imported; Anthropic-format models are excluded.",
  },
  {
    id: "opencode-zen",
    name: "OpenCode Zen",
    icon: ICON_OPENCODE,
    apiURL: "https://opencode.ai/zen/v1",
    modelsURL: "https://opencode.ai/zen/v1/models",
    authMethod: "bearer",
    apiKeyPlaceholder: "OpenCode API key",
    requiresApiKey: true,
    isLocal: false,
    supportsModelDiscovery: true,
    adapterId: "openai-compatible",
    verifiedCapabilities: ["chat"],
    notes:
      "Only models documented for /chat/completions are imported; Responses, Anthropic, and Gemini-format models are excluded.",
  },
  {
    id: "ollama",
    name: "Ollama (Local)",
    icon: ICON_OLLAMA,
    apiURL: "http://localhost:11434/v1/",
    authMethod: "none",
    requiresApiKey: false,
    isLocal: true,
    defaultModel: "llama3.3:70b",
    supportsModelDiscovery: true,
    verifiedCapabilities: ["chat", "embedding", "image"],
  },
  {
    id: "lmstudio",
    name: "LM Studio (Local)",
    icon: ICON_LMSTUDIO,
    apiURL: "http://localhost:1234/v1/",
    authMethod: "none",
    requiresApiKey: false,
    isLocal: true,
    supportsModelDiscovery: true,
    verifiedCapabilities: ["chat", "embedding"],
    notes: "Run LM Studio with a model loaded first",
  },
  {
    id: "azure",
    name: "Azure OpenAI",
    requiresApiKey: true,
    isLocal: false,
    icon: ICON_AZURE,
    apiURL:
      "https://{resource}.openai.azure.com/openai/deployments/{deployment}/",
    authMethod: "api-key-header",
    authHeaderName: "api-key",
    supportsModelDiscovery: false,
    adapterId: "azure-openai",
    verifiedCapabilities: ["chat", "embedding", "image", "tts", "stt"],
    notes: "Replace {resource} and {deployment} in URL",
  },
  {
    id: "nanogpt",
    name: "NanoGPT",
    icon: ICON_OPENROUTER,
    apiURL: "https://nano-gpt.com/api/v1",
    authMethod: "bearer",
    apiKeyPlaceholder: "nano-...",
    requiresApiKey: true,
    isLocal: false,
    supportsModelDiscovery: true,
    adapterId: "nanogpt",
    verifiedCapabilities: ["chat", "image", "video", "tts", "stt"],
  },
  {
    id: "hermes-agent",
    name: "Hermes Agent",
    icon: ICON_HERMES,
    apiURL: "http://localhost:8642/v1/",
    authMethod: "bearer",
    apiKeyPlaceholder: "change-me-local-dev",
    requiresApiKey: true,
    isLocal: true,
    isAgent: true,
    defaultModel: "hermes-agent",
    supportsModelDiscovery: true,
    verifiedCapabilities: ["chat"],
    notes:
      "Full research agent with terminal, file ops, web search. OpenAI-compatible API.",
  },
  {
    id: "opencode",
    name: "OpenCode",
    icon: ICON_OPENCODE,
    apiURL: "http://localhost:3000/v1/",
    authMethod: "none",
    requiresApiKey: false,
    isLocal: true,
    isAgent: true,
    supportsModelDiscovery: true,
    verifiedCapabilities: ["chat"],
    notes: "Coding agent. Run opencode serve first.",
  },
];

export function getPresetById(id: string): ProviderPreset | undefined {
  return providerPresets.find((p) => p.id === id);
}

export function getProviderPresets(): ProviderPreset[] {
  return providerPresets;
}
