// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "apiURL": string;
      "apiKey": string;
      "model": string;
      "datalabUseLocal": boolean;
      "datalabMode": string;
      "datalabUrl": string;
      "datalabApiKey": string;
      "mistralApiKey": string;
      "datalabMaxConcurrent": number;
      "aiMaxConcurrent": number;
      "localForceOcr": boolean;
      "cloudForceOcr": boolean;
      "cloudUseLlm": boolean;
      "modelConfigs": string;
      "activeModelId": string;
      "semanticScholarApiKey": string;
      "firecrawlApiKey": string;
      "firecrawlApiUrl": string;
      "firecrawlSearchLimit": number;
      "firecrawlMaxConcurrent": number;
      "webSearchProvider": string;
      "nanogptWebApiKey": string;
      "nanogptWebSearchLimit": number;
      "nanogptWebSearchDepth": string;
      "tavilyApiKey": string;
      "tavilySearchLimit": number;
      "tavilySearchDepth": string;
      "youdotcomApiKey": string;
      "youdotcomSearchMode": string;
      "youdotcomSearchLimit": number;
      "agenticMode": boolean;
      "libraryScope": string;
      "agentMaxResults": number;
      "agentMaxContentLength": number;
      "agentMaxIterations": number;
      "agentAutoOcr": boolean;
      "selectionMode": string;
      "searchAutoAiInsights": boolean;
      "searchAiInsightsPrompt": string;
      "searchAiInsightsResponseLength": number;
      "searchAiInsightsCitationStyle": string;
      "ragEnabled": boolean;
      "ragTokenThreshold": number;
      "ragTopK": number;
      "ragMinScore": number;
      "ragChunkSize": number;
      "ragChunkOverlap": number;
      "tableGenerationSound": boolean;
      "historySidebarWidth": number;
      "workspaceSidebarWidth": number;
      "workspaceSidebarCollapsed": boolean;
      "workspaceEditorHeight": number;
      "workspaceCustomPath": string;
      "workspaceFolderPaths": string;
      "fileViewerEnabled": boolean;
      "previewExtensions": string;
      "driveClientId": string;
      "driveClientSecret": string;
      "driveRefreshToken": string;
      "driveAccessToken": string;
      "driveTokenExpiry": string;
      "cloud.dropbox.clientId": string;
      "cloud.dropbox.refreshToken": string;
      "cloud.dropbox.accessToken": string;
      "cloud.dropbox.tokenExpiry": string;
      "cloud.nextcloud.serverUrl": string;
      "cloud.nextcloud.username": string;
      "cloud.nextcloud.appPassword": string;
      "cloud.box.clientId": string;
      "cloud.box.clientSecret": string;
      "cloud.box.refreshToken": string;
      "cloud.box.accessToken": string;
      "cloud.box.tokenExpiry": string;
      "cloud.onedrive.clientId": string;
      "cloud.onedrive.siteId": string;
      "cloud.onedrive.refreshToken": string;
      "cloud.onedrive.accessToken": string;
      "cloud.onedrive.tokenExpiry": string;
      "cloud.activeProvider": string;
    };
  }
}
