/**
 * Shared type definitions for the RAG (Retrieval-Augmented Generation) system.
 * Covers embedding API types, document chunks, vector storage, and retrieval.
 */

// ─── Embedding API Types (OpenAI-compatible) ───────────────────────────────

/** Request body for POST /v1/embeddings */
export interface EmbeddingRequest {
  input: string | string[];
  model: string;
  encoding_format?: "float" | "base64";
  dimensions?: number;
  user?: string;
}

/** Single embedding object in the response */
export interface EmbeddingData {
  object: "embedding";
  index: number;
  embedding: number[];
}

/** Response from POST /v1/embeddings */
export interface EmbeddingResponse {
  object: "list";
  data: EmbeddingData[];
  model: string;
  usage: {
    prompt_tokens: number;
    total_tokens: number;
  };
}

/** OpenAI-compatible error response */
export interface EmbeddingError {
  error: {
    message: string;
    type: string;
    param: string | null;
    code: string | null;
  };
}

/** Embedding model metadata from GET /api/v1/embedding-models */
export interface EmbeddingModelInfo {
  id: string;
  object: "model";
  created: number;
  owned_by: string;
  name?: string;
  description?: string;
  dimensions: number;
  supports_dimensions: boolean;
  max_tokens: number;
  pricing: {
    per_million_tokens: number;
    currency: string;
  };
}

/** Response from GET /api/v1/embedding-models */
export interface EmbeddingModelsListResponse {
  object: "list";
  data: EmbeddingModelInfo[];
}

// ─── Document Chunking Types ────────────────────────────────────────────────

/** Source type for a document chunk */
export type ChunkSource =
  | "pdf"
  | "note"
  | "abstract"
  | "metadata"
  | "table"
  | "file";

/** A single chunk of text from a document, ready for embedding */
export interface DocumentChunk {
  /** Unique ID: `${itemId}_${source}_${chunkIndex}` */
  id: string;
  /** Zotero item ID */
  itemId: number;
  /** The chunk text content */
  text: string;
  /** Where this chunk came from */
  source: ChunkSource;
  /** Position in the sequence of chunks for this source */
  chunkIndex: number;
  /** Additional metadata */
  metadata: {
    title?: string;
    authors?: string[];
    section?: string;
    startOffset: number;
    endOffset: number;
    /** Context text generated by contextual retrieval LLM (optional) */
    contextText?: string;
    /** Parent chunk ID for sentence-window retrieval (optional) */
    parentChunkId?: string;
    /** Child indices for parent chunks (optional) */
    childIndices?: number[];
    /** Sentence range [start, end] (optional) */
    windowRange?: [number, number];
  };
}

/** A chunk with its computed embedding vector */
export interface EmbeddedChunk extends DocumentChunk {
  embedding: number[];
  embeddingModel: string;
}

// ─── Vector Store Types ─────────────────────────────────────────────────────

/** Stored data for a single Zotero item's embeddings */
export interface VectorStoreEntry {
  itemId: number;
  chunks: EmbeddedChunk[];
  embeddingModel: string;
  dimensions: number;
  contentHash: string;
  indexedAt: string; // ISO date
  /** Parent windows for sentence-window retrieval (maps parent chunk ID → text) */
  parentWindows?: Record<string, string>;
}

/** Per-item metadata in the global index (no embedding vectors) */
export interface VectorIndexEntry {
  itemId: number;
  chunkCount: number;
  embeddingModel: string;
  dimensions: number;
  contentHash: string;
  lastIndexedAt: string; // ISO date
  /** Zotero item dateModified for fast staleness detection without content re-extraction */
  lastModified?: string;
  /** Cached at index time to avoid Zotero getField calls during search */
  title?: string;
  /** Cached at index time — first author surname */
  firstCreator?: string;
  /** Publication year extracted at index time */
  publicationYear?: number;
  /** ~300 char snippet from the abstract (or longest) chunk, cached at index time */
  snippet?: string;
}

/** Global index manifest file */
export interface VectorStoreIndex {
  version: number;
  entries: Record<number, VectorIndexEntry>; // keyed by itemId
  updatedAt: string; // ISO date
}

/** Statistics about the vector store */
export interface VectorStoreStats {
  totalItems: number;
  totalChunks: number;
  embeddingModel: string | null;
  dimensions: number | null;
}

/** Result from a vector similarity search, including mismatch diagnostics */
export interface VectorSearchResult {
  chunks: RetrievedChunk[];
  /**
   * True if stored vectors had different dimensions than the query vector.
   * When true, `chunks` will be empty — the caller should clear stale items
   * and re-index before retrying.
   */
  dimensionMismatch: boolean;
  /** Item IDs whose stored vectors had mismatched dimensions */
  mismatchedItemIds: number[];
}

// ─── Retrieval Types ────────────────────────────────────────────────────────

/** RAG pipeline step identifiers for progress reporting */
export type RAGProgressStep =
  | "indexing"
  | "embedding-query"
  | "searching"
  | "reranking"
  | "assembling"
  | "embedding-passthrough"
  | "graph-traversal"
  | "complete";

/** Progress event emitted during RAG retrieval */
export interface RAGProgressEvent {
  /** Current pipeline step */
  step: RAGProgressStep;
  /** Human-readable status message */
  message: string;
  /** Set to true when reporting an error state (step="complete" with error) */
  error?: boolean;
  /** Optional: ranked results available so far */
  rankedResults?: Array<{
    title: string;
    score: number;
    source: string;
    /** Preview of the chunk content (first ~300 chars) */
    description?: string;
    itemId: number;
    chunkId: string;
  }>;
  /** Optional: stats snapshot */
  stats?: {
    itemsToIndex?: number;
    itemsIndexed?: number;
    candidateCount?: number;
    selectedCount?: number;
    tokensUsed?: number;
    tier?: 1 | 2 | 3;
    segmentCount?: number;
  };
  /** Optional: generation evaluation metrics (when ragEvalEnabled) */
  evaluation?: GenerationEvalMetrics;
}

/** Callback for receiving RAG progress updates */
export type RAGProgressCallback = (event: RAGProgressEvent) => void;

/** Options for retrieval queries */
export interface RetrievalOptions {
  /** Maximum chunks to retrieve (default: 20) */
  topK?: number;
  /** Token budget for retrieved context */
  maxTokens?: number;
  /** Minimum cosine similarity threshold (default: 0.3) */
  minScore?: number;
  /** Enable re-ranking by source priority and position (default: true) */
  rerank?: boolean;
  /**
   * Verbatim context for non-indexable items (tables, files, topics).
   * Appended to the assembled RAG context without vector search.
   */
  passthroughContext?: string;
  /** Computed token budget from the model's context window */
  tokenBudget?: TokenBudget;
  /** Enable adaptive retrieval (CAR-style relevance cliff detection) */
  adaptiveRetrieval?: boolean;
  /** Enable hybrid search (BM25 + dense + RRF). Default: true */
  hybridSearch?: boolean;
  /** RRF alpha: weight for dense vs sparse (0-1, default 0.55). Higher = favor dense */
  rrfAlpha?: number;
  /** Enable MMR diversity selection (default: true) */
  mmrEnabled?: boolean;
  /** MMR lambda: relevance vs diversity trade-off (0-1, default 0.7). Higher = more relevance */
  mmrLambda?: number;
  /** Enable query expansion from selected item titles (default: true) */
  queryExpansion?: boolean;
  /** Enable multi-query variant generation for better recall (default: true) */
  multiQueryExpansion?: boolean;
  /** Enable parent-document expansion: boost other chunks from top papers (default: false) */
  parentExpansion?: boolean;
  /** Enable HyDE (Hypothetical Document Embeddings) query rewriting (default: false) */
  hydeEnabled?: boolean;
  /** Enable query decomposition for complex queries (default: false) */
  queryDecomposition?: boolean;
  /** Enable corrective RAG with re-retrieval on insufficient context (default: false) */
  correctiveEnabled?: boolean;
  /** Callback for live progress updates during retrieval */
  onProgress?: RAGProgressCallback;
}

/** A retrieved chunk with its relevance score */
export interface RetrievedChunk {
  chunk: EmbeddedChunk;
  /** Combined relevance score (0-1) */
  score: number;
  /** Source item info for attribution */
  sourceItem: {
    title: string;
    id: number;
    /** Publication year extracted from item (e.g. "2023") */
    publicationYear?: number;
  };
}

/** Result of a retrieval operation */
export interface RetrievalResult {
  /** Formatted context string ready for system prompt injection */
  context: string;
  /** Individual retrieved chunks with scores */
  chunks: RetrievedChunk[];
  /** Statistics about the retrieval */
  stats: RetrievalStats;
}

/** Statistics for a retrieval operation */
export interface RetrievalStats {
  totalChunksSearched: number;
  chunksRetrieved: number;
  tokensUsed: number;
  itemsIndexedOnDemand: number;
  queryTimeMs: number;
  /** Evaluation metrics (populated when ragEvalEnabled and ground truth matches) */
  evaluation?: RetrievalEvalMetrics;
}

// ─── Evaluation Types ────────────────────────────────────────────────────────

/** Ground truth entry for retrieval evaluation */
export interface GroundTruthEntry {
  query: string;
  relevant_item_ids: number[];
  description?: string;
  category?: "factual" | "analytical" | "comparative" | "entity_lookup";
}

/** Retrieval quality metrics */
export interface RetrievalEvalMetrics {
  recall_at_k: Record<number, number>;
  precision_at_k: Record<number, number>;
  mrr: number;
  ndcg_at_k: Record<number, number>;
  hit_rate: number;
  num_retrieved: number;
  num_relevant_total: number;
}

/** Generation quality metrics (LLM-as-judge) */
export interface GenerationEvalMetrics {
  faithfulness: number;
  answer_relevancy: number;
  context_precision: number;
  hallucination_rate: number;
}

// ─── RAG Configuration ──────────────────────────────────────────────────────

/** Runtime RAG configuration derived from preferences */
export interface RAGConfig {
  enabled: boolean;
  tokenThreshold: number;
  topK: number;
  minScore: number;
  chunkSize: number;
  chunkOverlap: number;
  adaptiveRetrieval?: boolean; // Enable CAR-style adaptive chunk selection (default: true)
  minScoreThreshold?: number; // Floor threshold for any result (default: 0.3)
  rrfAlpha?: number; // RRF weight for dense vs sparse (0-1, default 0.55)
  mmrEnabled?: boolean; // Enable MMR diversity selection (default: true)
  mmrLambda?: number; // MMR relevance-diversity trade-off (0-1, default 0.7)
  queryExpansion?: boolean; // Enable query expansion from selected item titles (default: true)
  multiQueryExpansion?: boolean; // Enable multi-query variant generation (default: true)
  hydeEnabled?: boolean; // Enable HyDE (Hypothetical Document Embeddings) query rewriting (default: false)
  contextualRetrieval?: boolean; // Enable contextual retrieval at index time (default: false)
  sentenceWindow?: boolean; // Enable sentence-window retrieval (default: false)
  sentenceWindowSize?: number; // Sentences on each side of child chunk (default: 3)
  queryDecomposition?: boolean; // Enable query decomposition for complex queries (default: false)
  citationGraphHops?: number; // Number of hops for citation graph traversal (default: 0, disabled)
  correctiveEnabled?: boolean; // Enable corrective RAG with re-retrieval (default: false)
}

/** Default RAG configuration values */
export const DEFAULT_RAG_CONFIG: RAGConfig = {
  enabled: true,
  tokenThreshold: 16000,
  topK: 20,
  minScore: 0.3,
  chunkSize: 512,
  chunkOverlap: 64,
  adaptiveRetrieval: true,
  minScoreThreshold: 0.3,
  rrfAlpha: 0.55,
  mmrEnabled: true,
  mmrLambda: 0.7,
  queryExpansion: true,
  multiQueryExpansion: true,
  hydeEnabled: false,
  contextualRetrieval: false,
  sentenceWindow: false,
  sentenceWindowSize: 3,
  queryDecomposition: false,
  citationGraphHops: 0,
  correctiveEnabled: false,
};

// ─── Token Budget Types ─────────────────────────────────────────────────────

/** Token budget computed from the model's context window */
export interface TokenBudget {
  /** Total model context window (tokens) */
  contextLength: number;
  /** Estimated system prompt size (tokens) */
  systemPromptTokens: number;
  /** All conversation history (tokens) */
  conversationTokens: number;
  /** Web search results (tokens) */
  webResultTokens: number;
  /** Reserved for model response (tokens) */
  reservedOutputTokens: number;
  /** Safety buffer — 5% of contextLength */
  safetyMargin: number;
  /** What's left for RAG chunks + passthrough content */
  availableForContent: number;
}
