pref("enable", true);
pref("input", "This is input");
pref("apiURL", "https://api.openai.com/v1/");
pref("apiKey", "");
pref("model", "gpt-5-mini");
pref("datalabUseLocal", false);
pref("datalabUrl", "http://localhost:8001");
pref("datalabApiKey", "");
pref("datalabMaxConcurrent", 5);
pref("localForceOcr", true);
pref("cloudForceOcr", false);
pref("cloudUseLlm", false);
pref("modelConfigs", "[]");
pref("activeModelId", "");
